// "Manual-only" collection-log items — clog rewards the plugin CANNOT drop-track because they're
// bought from a points/currency shop, gambled, or handed over by a reward interface (no loot event
// ever fires). The only auto-signal is the one-time in-game "New item added to your collection log"
// line, so a member who already owns the item must submit it manually.
//
// The ID set is generated by scripts/build-clog-dataset.mjs (see NON_LOOT_ACTIVITIES there) into the
// tiny clogManualIds.json, kept separate from the 140 KB clog.json so client components can import
// it cheaply. Curation is conservative — uncertain sources stay "tracked", so a badge never wrongly
// claims a real drop won't be tracked.
import manualIds from '@/data/clogManualIds.json';

export const MANUAL_ONLY_CLOG_IDS: ReadonlySet<number> = new Set(manualIds as number[]);

export function isManualOnlyItemId(id: number): boolean {
  return MANUAL_ONLY_CLOG_IDS.has(id);
}

function parseTrackedIds(trackedItemIds: string | number[] | null | undefined): number[] {
  if (!trackedItemIds) return [];
  if (Array.isArray(trackedItemIds)) return trackedItemIds;
  try {
    const arr = JSON.parse(trackedItemIds);
    return Array.isArray(arr) ? (arr as number[]) : [];
  } catch {
    return [];
  }
}

// True when a drop tile tracks at least one item and EVERY tracked item is manual-only — i.e. the
// plugin can't auto-detect it as a drop. Accepts the raw JSON string or a parsed id array.
export function isManualOnlyDropTile(tile: {
  tileType?: string | null;
  trackedItemIds?: string | number[] | null;
}): boolean {
  if (tile.tileType !== 'drop') return false;
  const ids = parseTrackedIds(tile.trackedItemIds);
  return ids.length > 0 && ids.every((id) => MANUAL_ONLY_CLOG_IDS.has(id));
}
