// Fun one-liners the Anvil plugin may post on a player's death (1/100 roll, otherwise
// the player's own configured message is used). `{name}` is substituted with the RSN.
// Served via GET /api/plugin/config so the pool can be edited without a plugin release;
// the plugin keeps a small baked-in fallback for when it's offline.
export const FUN_DEATH_MESSAGES: string[] = [
  "{name} has been sent to Lumbridge to think about their choices.",
  "{name} forgot to flick Protect from Magic. Classic.",
  "{name} died doing what they loved: not eating.",
  "GG {name}, the gravestone fund thanks you for your donation.",
  "{name} has logged out to the respawn screen.",
  "{name} found out the hard way that it does, in fact, hit through prayer.",
  "{name} bravely tanked one more hit than they had HP for.",
  "Press F for {name}.",
  "{name} just speedran a trip to Lumbridge.",
  "{name} would like to remind everyone that food is optional, apparently.",
];

export const SKILLS = [
  "overall",
  "attack",
  "defence",
  "strength",
  "hitpoints",
  "ranged",
  "prayer",
  "magic",
  "cooking",
  "woodcutting",
  "fletching",
  "fishing",
  "firemaking",
  "crafting",
  "smithing",
  "mining",
  "herblore",
  "agility",
  "thieving",
  "slayer",
  "farming",
  "runecraft",
  "hunter",
  "construction",
  "sailing",
] as const;

export const SKILL_LABELS: Record<string, string> = {
  overall: "Total",
  attack: "Attack",
  defence: "Defence",
  strength: "Strength",
  hitpoints: "Hitpoints",
  ranged: "Ranged",
  prayer: "Prayer",
  magic: "Magic",
  cooking: "Cooking",
  woodcutting: "Woodcutting",
  fletching: "Fletching",
  fishing: "Fishing",
  firemaking: "Firemaking",
  crafting: "Crafting",
  smithing: "Smithing",
  mining: "Mining",
  herblore: "Herblore",
  agility: "Agility",
  thieving: "Thieving",
  slayer: "Slayer",
  farming: "Farming",
  runecraft: "Runecraft",
  hunter: "Hunter",
  construction: "Construction",
  sailing: "Sailing",
};

export const BOSSES: { key: string; label: string }[] = [
  { key: "abyssalSire", label: "Abyssal Sire" },
  { key: "alchemicalHydra", label: "Alchemical Hydra" },
  { key: "amoxliatl", label: "Amoxliatl" },
  { key: "araxxor", label: "Araxxor" },
  { key: "artio", label: "Artio" },
  { key: "barrows", label: "Barrows" },
  { key: "bryophyta", label: "Bryophyta" },
  { key: "callisto", label: "Callisto" },
  { key: "calvarion", label: "Calvar'ion" },
  { key: "cerberus", label: "Cerberus" },
  { key: "chambersOfXeric", label: "Chambers of Xeric" },
  { key: "chambersOfXericChallengeMode", label: "CoX: CM" },
  { key: "chaosElemental", label: "Chaos Elemental" },
  { key: "chaosFanatic", label: "Chaos Fanatic" },
  { key: "commanderZilyana", label: "Commander Zilyana" },
  { key: "corporealBeast", label: "Corporeal Beast" },
  { key: "crazyArchaeologist", label: "Crazy Archaeologist" },
  { key: "dagannothPrime", label: "Dagannoth Prime" },
  { key: "dagannothRex", label: "Dagannoth Rex" },
  { key: "dagannothSupreme", label: "Dagannoth Supreme" },
  { key: "derangedArchaeologist", label: "Deranged Archaeologist" },
  { key: "dukeSucellus", label: "Duke Sucellus" },
  { key: "generalGraardor", label: "General Graardor" },
  { key: "giantMole", label: "Giant Mole" },
  { key: "grotesqueGuardians", label: "Grotesque Guardians" },
  { key: "hespori", label: "Hespori" },
  { key: "kalphiteQueen", label: "Kalphite Queen" },
  { key: "kingBlackDragon", label: "King Black Dragon" },
  { key: "kraken", label: "Kraken" },
  { key: "kreeArra", label: "Kree'Arra" },
  { key: "krilTsutsaroth", label: "K'ril Tsutsaroth" },
  { key: "lunarChests", label: "Lunar Chests" },
  { key: "mimic", label: "Mimic" },
  { key: "nex", label: "Nex" },
  { key: "nightmare", label: "Nightmare" },
  { key: "phosanisNightmare", label: "Phosani's Nightmare" },
  { key: "obor", label: "Obor" },
  { key: "phantomMuspah", label: "Phantom Muspah" },
  { key: "sarachnis", label: "Sarachnis" },
  { key: "scorpia", label: "Scorpia" },
  { key: "scurrius", label: "Scurrius" },
  { key: "skotizo", label: "Skotizo" },
  { key: "solHeredit", label: "Sol Heredit" },
  { key: "spindel", label: "Spindel" },
  { key: "tempoross", label: "Tempoross" },
  { key: "gauntlet", label: "The Gauntlet" },
  { key: "corruptedGauntlet", label: "Corrupted Gauntlet" },
  { key: "hueycoatl", label: "The Hueycoatl" },
  { key: "leviathan", label: "The Leviathan" },
  { key: "whisperer", label: "The Whisperer" },
  { key: "theatreOfBlood", label: "Theatre of Blood" },
  { key: "theatreOfBloodHardMode", label: "ToB: HM" },
  { key: "thermonuclearSmokeDevil", label: "Thermy" },
  { key: "tombsOfAmascut", label: "Tombs of Amascut" },
  { key: "tombsOfAmascutExpertMode", label: "ToA: Expert" },
  { key: "tzKalZuk", label: "TzKal-Zuk" },
  { key: "tzTokJad", label: "TzTok-Jad" },
  { key: "vardorvis", label: "Vardorvis" },
  { key: "venenatis", label: "Venenatis" },
  { key: "vetion", label: "Vet'ion" },
  { key: "vorkath", label: "Vorkath" },
  { key: "wintertodt", label: "Wintertodt" },
  { key: "zalcano", label: "Zalcano" },
  { key: "zulrah", label: "Zulrah" },
  { key: "doomOfMokhaiotl", label: "Doom of Mokhaiotl" },
  { key: "royalTitans", label: "The Royal Titans" },
  { key: "yama", label: "Yama" },
  { key: "maggotKing", label: "Maggot King" },
];
