// EHP (efficient hours played) and EHB (efficient hours bossed), computed here rather than fetched.
//
// EHB is the easy half: every boss has a kills-per-hour rate, and your EHB is the sum of
// `killcount / rate`. EHP is the involved one — each skill carries a list of XP brackets with the
// best rate available from that XP onward, so a skill's time is a piecewise integral, and then bonus
// XP has to be accounted for: training Slayer hands you Attack XP, Firemaking hands you Thieving XP
// (Firefact), and so on. Time you'd have spent training a skill that arrives free from elsewhere
// isn't time you played.
//
// The rate tables are third-party data (src/data/efficiencyRates.json, regenerated by
// `npm run data:efficiency`) because keeping rates current is a full-time community job. The
// ALGORITHM is ours to run: we already hold a hiscores snapshot for every member every 15 minutes,
// so computing locally is fresher than asking an API about players it may not track, works offline
// for self-hosted instances, and doesn't put someone else's rate limit between a clan and its
// leaderboard.
//
// This is a faithful port of a third-party MIT-licensed efficiency algorithm (attribution in
// THIRD_PARTY_NOTICES.md). Faithful on purpose: agreeing with the number everyone else quotes is the
// whole point of the metric, and scripts/verify-efficiency.mjs checks our output against the
// reference for real accounts. Where this reads oddly, it reads oddly there too — resist tidying it
// without re-running that check.

import type { HiscoresSnapshot } from '@/lib/hiscores';
import { SKILLS } from '@/lib/constants';
import rateData from '@/data/efficiencyRates.json';

export const MAX_SKILL_EXP = 200_000_000;
export const SKILL_EXP_AT_99 = 13_034_431;

/** Every trainable skill — "overall" is the sum, not a skill you can put hours into. */
const REAL_SKILLS: string[] = SKILLS.filter((s) => s !== 'overall');

export interface SkillMethod {
  startExp: number;
  rate: number;
  /** The rate without assumed incoming bonus XP; only the scaled-bonus maths uses it. */
  realRate?: number;
}
export interface SkillBonus {
  originSkill: string;
  bonusSkill: string;
  startExp: number;
  endExp: number;
  /** false = XP you effectively already have; true = XP that will arrive before you finish. */
  end: boolean;
  ratio: number;
  maxBonus?: number;
}
export interface SkillMeta {
  skill: string;
  methods: SkillMethod[];
  bonuses: SkillBonus[];
}
export interface AlgorithmTables {
  skills: SkillMeta[];
  bosses: Record<string, number>;
}

/** Account shapes the rate tables cover. We select `main` until we detect account type. */
export type AlgorithmType =
  | 'main' | 'ironman' | 'ultimate' | 'def1'
  | 'lvl3' | 'f2p' | 'f2p_lvl3' | 'f2p_ironman' | 'f2p_lvl3_ironman';

const TABLES = (rateData as { algorithms: Record<string, AlgorithmTables> }).algorithms;

export interface EfficiencyResult {
  /** Efficient hours played — skilling time at the best known rates. */
  ehp: number;
  /** Efficient hours bossed — boss killcount converted to hours. */
  ehb: number;
  ehpBySkill: Record<string, number>;
  ehbByBoss: Record<string, number>;
  /** Hours from here to all 99s, and to 200m all. Free once EHP is computed. */
  ttm: number;
  tt200m: number;
}

const round5 = (n: number) => Math.round(n * 1e5) / 1e5;

/**
 * One algorithm variant, with the derived structures cached. Building these costs a pass over the
 * bonus rules and a full max-EHP computation, so a variant is constructed once and reused for every
 * member of every sweep.
 */
class EfficiencyAlgorithm {
  private readonly skillMetas: Map<string, SkillMeta>;
  private readonly bossRates: Record<string, number>;
  private readonly startBonuses: SkillBonus[];
  private readonly endBonuses: SkillBonus[];
  /** originSkill → the skills its training also feeds. */
  private readonly bonusDirection: Map<string, string[]>;
  private readonly maximumEHP: Map<string, number>;

  constructor(tables: AlgorithmTables) {
    this.skillMetas = new Map(tables.skills.map((s) => [s.skill, s]));
    this.bossRates = tables.bosses;

    const all = tables.skills.flatMap((s) => s.bonuses);
    this.bonusDirection = new Map();
    for (const b of all) {
      const list = this.bonusDirection.get(b.originSkill);
      if (!list) this.bonusDirection.set(b.originSkill, [b.bonusSkill]);
      else if (!list.includes(b.bonusSkill)) list.push(b.bonusSkill);
    }

    // Sorted once here rather than on every call: the order depends only on how many skills each
    // bonus target itself feeds, which is a property of the table, not of anyone's stats. It puts
    // skills that receive no bonus XP first (Slayer), so their contribution is settled before
    // anything downstream reads it.
    const byDependencies = (a: SkillBonus, b: SkillBonus) =>
      (this.bonusDirection.get(b.bonusSkill)?.length ?? 0) - (this.bonusDirection.get(a.bonusSkill)?.length ?? 0);
    this.startBonuses = all.filter((b) => !b.end).sort(byDependencies);
    this.endBonuses = all.filter((b) => b.end).sort(byDependencies);

    this.maximumEHP = this.computeMaximumEHP();
  }

  // ---- public ----------------------------------------------------------------------

  ehb(killcounts: Map<string, number>): { total: number; byBoss: Record<string, number> } {
    const byBoss: Record<string, number> = {};
    let total = 0;
    for (const [boss, rate] of Object.entries(this.bossRates)) {
      if (!rate || rate <= 0) continue;
      const kc = Math.max(0, killcounts.get(boss) ?? 0);
      const hours = round5(kc / rate);
      byBoss[boss] = hours;
      total += hours;
    }
    return { total, byBoss };
  }

  ehp(stats: Map<string, number>): { total: number; bySkill: Record<string, number> } {
    const fixed = new Map<string, number>();
    for (const skill of REAL_SKILLS) fixed.set(skill, Math.max(0, stats.get(skill) ?? 0));

    const startBonusExp = this.bonusExp(fixed, false);
    const endBonusExp = this.bonusExp(fixed, true);

    const bySkill: Record<string, number> = {};
    let total = 0;

    for (const originSkill of REAL_SKILLS) {
      let timeSum = 0;

      // Bonuses chain: Woodcutting feeds Firemaking, which feeds Cooking. Zeroing Woodcutting
      // therefore changes Cooking's time too, so the indirect targets have to be walked as well or
      // its EHP comes out short.
      const bonusSkills = new Set(this.bonusDirection.get(originSkill) ?? []);
      for (const bonusSkill of [...bonusSkills]) {
        for (const dependant of this.bonusDirection.get(bonusSkill) ?? []) bonusSkills.add(dependant);
      }

      for (const bonusSkill of [...bonusSkills, originSkill]) {
        const startExp = (fixed.get(bonusSkill) ?? 0) + (startBonusExp.get(bonusSkill) ?? 0);
        const endExp = MAX_SKILL_EXP - (endBonusExp.get(bonusSkill) ?? 0);
        const maxed = endExp - startExp <= 0;
        if (maxed && bonusSkill !== originSkill) continue;

        // A skill's EHP is the time it SAVED you: what training it from zero would have cost, minus
        // what remains. Recomputing the bonuses against a zeroed origin skill is what stops bonus XP
        // being credited twice.
        const reset = new Map(fixed);
        reset.set(originSkill, 0);
        const startReset = this.bonusExp(reset, false);
        const endReset = this.bonusExp(reset, true);

        const startExpReset = (reset.get(bonusSkill) ?? 0) + (startReset.get(bonusSkill) ?? 0);
        const endExpReset = MAX_SKILL_EXP - (endReset.get(bonusSkill) ?? 0);

        const diff =
          this.skillTime(bonusSkill, startExpReset, endExpReset) - this.skillTime(bonusSkill, startExp, endExp);

        // Overtrained past the point the tables model: credit the skill's own ceiling, not a number
        // inflated by bonus XP it can no longer absorb.
        timeSum += maxed ? Math.min(this.maximumEHP.get(bonusSkill) ?? Infinity, diff) : diff;
      }

      const hours = round5(timeSum);
      bySkill[originSkill] = hours;
      total += hours;
    }

    return { total, bySkill };
  }

  /** Hours from these stats to all 99s. */
  ttm(stats: Map<string, number>): number {
    const maxed = new Map(REAL_SKILLS.map((s) => [s, SKILL_EXP_AT_99]));
    const capped = new Map(REAL_SKILLS.map((s) => [s, Math.min(stats.get(s) ?? 0, SKILL_EXP_AT_99)]));
    return this.ehp(maxed).total - this.ehp(capped).total;
  }

  /** Hours from these stats to 200m in everything. */
  tt200m(stats: Map<string, number>): number {
    return (this.maximumEHP.get('__overall__') ?? 0) - this.ehp(stats).total;
  }

  // ---- internals -------------------------------------------------------------------

  /**
   * How much XP each skill receives for free, either already (start) or before it's finished (end).
   * Three pairs don't scale linearly — drift net (Hunter→Fishing), swimming (Thieving→Agility) and
   * Firefact (Firemaking→Thieving) can hand over more than the origin skill could ever actually
   * generate, so those are capped by what the method genuinely produces.
   */
  private bonusExp(stats: Map<string, number>, end: boolean): Map<string, number> {
    const map = new Map<string, number>(REAL_SKILLS.map((s) => [s, 0]));
    const bonuses = end ? this.endBonuses : this.startBonuses;

    for (const b of bonuses) {
      if (end) {
        const scaled = this.scaledBonus(stats, b);
        if (scaled !== null) {
          map.set(b.bonusSkill, (map.get(b.bonusSkill) ?? 0) + scaled);
          continue;
        }
      }
      const expCap = Math.min(b.endExp, MAX_SKILL_EXP);
      const originStart =
        Math.max(stats.get(b.originSkill) ?? 0, b.startExp) + (end ? 0 : (map.get(b.originSkill) ?? 0));
      const originEnd = end ? expCap - (map.get(b.originSkill) ?? 0) : expCap;
      const toApply = Math.max(0, originEnd - originStart) * b.ratio;
      map.set(b.bonusSkill, Math.min(MAX_SKILL_EXP, (map.get(b.bonusSkill) ?? 0) + toApply));
    }
    return map;
  }

  /** The three special-cased pairs; null means "this bonus scales normally". */
  private scaledBonus(stats: Map<string, number>, b: SkillBonus): number | null {
    const SPECIAL: Record<string, string> = {
      'hunter>fishing': 'hunter',
      'thieving>agility': 'thieving',
      'firemaking>thieving': 'firemaking',
    };
    if (SPECIAL[`${b.originSkill}>${b.bonusSkill}`] === undefined) return null;

    const originMeta = this.skillMetas.get(b.originSkill);
    const bonusMeta = this.skillMetas.get(b.bonusSkill);
    const originMethod = originMeta?.methods.find((m) => !!m.realRate);
    const bonusMethod = bonusMeta?.methods.at(-1);
    const ratio = originMeta?.bonuses[0]?.ratio;
    if (!originMethod || !bonusMethod || !ratio) return null;

    const originStart = Math.max(originMethod.startExp, stats.get(b.originSkill) ?? 0);
    const originExpLeft = MAX_SKILL_EXP - originStart;

    const realTime =
      this.skillTime(b.originSkill, originStart, MAX_SKILL_EXP, true) +
      this.skillTime(b.bonusSkill, stats.get(b.bonusSkill) ?? 0, MAX_SKILL_EXP, true);
    const fakeTime =
      this.skillTime(b.originSkill, originStart, MAX_SKILL_EXP, false) +
      this.skillTime(b.bonusSkill, stats.get(b.bonusSkill) ?? 0, MAX_SKILL_EXP, false);

    const excess = (realTime - fakeTime) * bonusMethod.rate;
    return originExpLeft * ratio - excess;
  }

  /** Hours to take one skill from startExp to endExp, integrated across its rate brackets. */
  private skillTime(skill: string, startExp: number, endExp: number, useRealRates = false): number {
    const methods = this.skillMetas.get(skill)?.methods;
    // Skills the tables don't cover (Hitpoints, Magic, Fletching) come free with other training.
    // The fraction keeps them ordered rather than exactly zero, matching the reference implementation.
    if (!methods || (methods.length === 1 && methods[0].rate === 0)) {
      return (endExp - startExp) / MAX_SKILL_EXP;
    }

    let time = 0;
    for (let i = 0; i < methods.length; i++) {
      const current = methods[i];
      const next = methods[i + 1];
      if (current.rate === 0) continue;
      const rate = useRealRates && current.realRate ? current.realRate : current.rate;

      if (next && next.startExp > startExp && current.startExp < endExp) {
        time += (Math.min(next.startExp, endExp) - Math.max(startExp, current.startExp)) / rate;
      }
      if (!next && endExp > current.startExp) {
        time += (endExp - Math.max(current.startExp, startExp)) / rate;
      }
    }
    return time;
  }

  /** Each skill's ceiling: hours from nothing to 200m, which caps overtrained skills. */
  private computeMaximumEHP(): Map<string, number> {
    const zero = new Map<string, number>(REAL_SKILLS.map((s) => [s, 0]));
    const startBonus = this.bonusExp(zero, false);
    const endBonus = this.bonusExp(zero, true);

    const map = new Map<string, number>();
    let total = 0;
    for (const skill of REAL_SKILLS) {
      const hours = this.skillTime(
        skill,
        startBonus.get(skill) ?? 0,
        MAX_SKILL_EXP - (endBonus.get(skill) ?? 0),
      );
      map.set(skill, hours);
      total += hours;
    }
    map.set('__overall__', total);
    return map;
  }
}

// One instance per variant, built lazily and kept — the derived tables are stats-independent.
const instances = new Map<AlgorithmType, EfficiencyAlgorithm>();
function algorithm(type: AlgorithmType = 'main'): EfficiencyAlgorithm {
  let instance = instances.get(type);
  if (!instance) {
    const tables = TABLES[type];
    if (!tables) throw new Error(`No efficiency tables for algorithm "${type}"`);
    instance = new EfficiencyAlgorithm(tables);
    instances.set(type, instance);
  }
  return instance;
}

/** XP per skill from a snapshot, with unranked (-1) read as zero. */
export function experienceMap(snapshot: HiscoresSnapshot): Map<string, number> {
  const map = new Map<string, number>();
  for (const skill of REAL_SKILLS) map.set(skill, Math.max(0, snapshot.skills?.[skill]?.xp ?? 0));
  return map;
}

/** Killcount per boss from a snapshot, with unranked (-1) read as zero. */
export function killcountMap(snapshot: HiscoresSnapshot): Map<string, number> {
  const map = new Map<string, number>();
  for (const [boss, entry] of Object.entries(snapshot.bosses ?? {})) {
    map.set(boss, Math.max(0, entry?.score ?? 0));
  }
  return map;
}

/**
 * The whole efficiency picture for one snapshot. Cheap enough (sub-millisecond) to call per member
 * per sweep; no I/O.
 */
export function computeEfficiency(snapshot: HiscoresSnapshot, type: AlgorithmType = 'main'): EfficiencyResult {
  const algo = algorithm(type);
  const stats = experienceMap(snapshot);
  const { total: ehp, bySkill: ehpBySkill } = algo.ehp(stats);
  const { total: ehb, byBoss: ehbByBoss } = algo.ehb(killcountMap(snapshot));
  return {
    ehp: round5(ehp),
    ehb: round5(ehb),
    ehpBySkill,
    ehbByBoss,
    ttm: round5(Math.max(0, algo.ttm(stats))),
    tt200m: round5(Math.max(0, algo.tt200m(stats))),
  };
}

/** Just the two headline numbers — what a competition metric reads. */
export function computeEhpEhb(snapshot: HiscoresSnapshot, type: AlgorithmType = 'main'): { ehp: number; ehb: number } {
  const algo = algorithm(type);
  return {
    ehp: round5(algo.ehp(experienceMap(snapshot)).total),
    ehb: round5(algo.ehb(killcountMap(snapshot)).total),
  };
}
