import raidRewards from '@/data/raidRewards.json';
import type { LuckRateSource } from '@/lib/clogProfile';

// Raid luck, and the one number we have to assume to get it.
//
// A raid is not a kill table. The chest rolls ONE unique with a chance that depends on how the raid
// went — points at Chambers of Xeric, invocation level at Tombs of Amascut — and only then picks
// which unique it is. The wiki gives us the second half exactly (each item's share of the unique
// table, in src/data/raidRewards.json, regenerated by `npm run data:drops`). The first half the
// hiscores cannot tell us: they record completions and nothing else — no points, no invocation, no
// party size, and in a team the purple goes to one player rather than to everyone.
//
// So that half is an ASSUMPTION, stated in one place, and overridable per clan via the
// `raid_luck_rates` setting. A clan that duos 40-invocation Tombs and one that mass-runs Entry Mode
// are not the same, and no single default is right for both — but a stated assumption a clan can
// correct beats either silence or a number pretending to be measured.
//
// The two halves multiply: a Twisted bow is 1-in-30 of the Chambers unique table, so at an assumed
// 1-in-30 personal unique chance it lands at 1-in-900 per raid.

export const RAID_LUCK_SETTING_KEY = 'raid_luck_rates';

/**
 * Assumed chance that a given raid ends with a unique FOR THIS PLAYER — after points/invocation and
 * after the team split. Deliberately a single knob: it is the only thing we cannot observe, and
 * splitting it into points × party size would be three guesses wearing a trench coat.
 */
export const DEFAULT_RAID_UNIQUE_CHANCE: Record<string, number> = {
  chambersOfXeric: 30,
  chambersOfXericChallengeMode: 23,
  theatreOfBlood: 45,
  theatreOfBloodHardMode: 40,
  tombsOfAmascut: 35,
  tombsOfAmascutExpertMode: 25,
};

interface RaidTable {
  label: string;
  chest: string;
  items: { i: number; d: number }[];
}

/** Admin overrides merge over the defaults; anything unparseable is ignored rather than trusted. */
export function raidUniqueChances(overrides?: unknown): Record<string, number> {
  const merged = { ...DEFAULT_RAID_UNIQUE_CHANCE };
  if (overrides && typeof overrides === 'object') {
    for (const [key, value] of Object.entries(overrides as Record<string, unknown>)) {
      const n = typeof value === 'number' ? value : Number(value);
      if (Number.isFinite(n) && n > 0) merged[key] = n;
    }
  }
  return merged;
}

/**
 * Item id → the raid sources that drop it, as ordinary luck sources.
 *
 * Expressed in the same shape as a monster drop so the luck engine needs no special case: a raid is
 * simply another source with a 1-in-N, and an item that comes from both a raid and a boss adds its
 * expectations like any other multi-source drop.
 */
export function raidSourcesByItem(overrides?: unknown): Map<number, LuckRateSource[]> {
  const chances = raidUniqueChances(overrides);
  const tables = raidRewards as unknown as Record<string, RaidTable>;
  const out = new Map<number, LuckRateSource[]>();

  for (const [bossKey, table] of Object.entries(tables)) {
    const unique = chances[bossKey];
    if (!Number.isFinite(unique) || unique <= 0) continue;
    for (const item of table.items) {
      if (!Number.isFinite(item.d) || item.d <= 0) continue;
      const list = out.get(item.i) ?? [];
      list.push({
        source: table.label,
        bossKey,
        // Two independent steps: does this raid give me a unique, and is it this one.
        denominator: Math.round(unique * item.d * 100) / 100,
        rolls: 1,
        bundle: 1,
        assumed: true,
      });
      out.set(item.i, list);
    }
  }
  return out;
}
