import raidRewards from '@/data/raidRewards.json';
import { clogItemNames } from '@/lib/clogDataset';
import type { LuckRateSource } from '@/lib/clogProfile';

// Raid luck, and the one number we have to assume to get it.
//
// A raid is not a kill table. The chest rolls ONE unique with a chance that depends on how the raid
// went — points at Chambers of Xeric, invocation level at Tombs of Amascut — and only then picks
// which unique it is. The wiki gives us the second half exactly (each item's share of the unique
// table, in src/data/raidRewards.json, regenerated by `npm run data:drops`). The first half the
// hiscores cannot tell us: they record completions and nothing else — no points, no invocation, no
// party size, and in a team the purple goes to one player rather than to everyone.
//
// So that half is an ASSUMPTION, stated in one place, and overridable per clan via the
// `raid_luck_rates` setting. A clan that duos 40-invocation Tombs and one that mass-runs Entry Mode
// are not the same, and no single default is right for both — but a stated assumption a clan can
// correct beats either silence or a number pretending to be measured.
//
// The two halves multiply: a Twisted bow is 1-in-30 of the Chambers unique table, so at an assumed
// 1-in-30 personal unique chance it lands at 1-in-900 per raid.

export const RAID_LUCK_SETTING_KEY = 'raid_luck_rates';

/**
 * Assumed chance that a given raid ends with a unique FOR THIS PLAYER — after points/invocation and
 * after the team split. Deliberately a single knob: it is the only thing we cannot observe, and
 * splitting it into points × party size would be three guesses wearing a trench coat.
 */
export const DEFAULT_RAID_UNIQUE_CHANCE: Record<string, number> = {
  chambersOfXeric: 30,
  chambersOfXericChallengeMode: 23,
  theatreOfBlood: 45,
  theatreOfBloodHardMode: 40,
  tombsOfAmascut: 35,
  tombsOfAmascutExpertMode: 25,
};

interface RaidTable {
  label: string;
  chest: string;
  items: { i: number; d: number }[];
}

/** Admin overrides merge over the defaults; anything unparseable is ignored rather than trusted. */
export function raidUniqueChances(overrides?: unknown): Record<string, number> {
  const merged = { ...DEFAULT_RAID_UNIQUE_CHANCE };
  if (overrides && typeof overrides === 'object') {
    for (const [key, value] of Object.entries(overrides as Record<string, unknown>)) {
      const n = typeof value === 'number' ? value : Number(value);
      if (Number.isFinite(n) && n > 0) merged[key] = n;
    }
  }
  return merged;
}

/**
 * Item id → the raid sources that drop it, as ordinary luck sources.
 *
 * Expressed in the same shape as a monster drop so the luck engine needs no special case: a raid is
 * simply another source with a 1-in-N, and an item that comes from both a raid and a boss adds its
 * expectations like any other multi-source drop.
 */
/**
 * Tiers that roll their base raid's unique table, differing only in how often a unique appears.
 *
 * The dataset has no table of their own for these, so their killcount was worth exactly nothing:
 * `DEFAULT_RAID_UNIQUE_CHANCE` named them, the loop below never reached them, and a Challenge Mode
 * or Expert raider had their whole KC scored as zero expectation — which is the shape that puts
 * somebody on the spooned board for ordinary luck.
 *
 * Theatre of Blood is absent on purpose: hard mode HAS its own table (the same seven uniques), so
 * it already resolves.
 */
const SHARES_UNIQUE_TABLE: Record<string, { base: string; label: string }> = {
  chambersOfXericChallengeMode: { base: 'chambersOfXeric', label: 'Chambers of Xeric (challenge mode)' },
  tombsOfAmascutExpertMode: { base: 'tombsOfAmascut', label: 'Tombs of Amascut (expert mode)' },
};

/**
 * Raid rewards a per-kill rate cannot describe, so the luck board leaves them alone.
 *
 * TWO KINDS, both of which put people on the spooned board for nothing.
 *
 * SUPPLY TIERS. A raid chest rolls one big group of bulk consumables — death runes, grimy herbs,
 * ores, uncut gems — filed at a single share alongside the uniques. Almost none of them are
 * collection log items, so they never reached the board; the two or three that ARE (Dark relic,
 * Torn prayer scroll, Cache of runes) were modelled at 1-in-990 raids while arriving every few.
 * One member showed 72 dark relics against 1.4 expected. Detected rather than listed: a tier is
 * supply when it is a crowd and the collection log wants almost none of it, which is what separates
 * Chambers' 33 items from Theatre hard mode's five uniques that happen to share a rate.
 *
 * STACKS. The collection log counts ITEMS, not drops, so one roll that pays 30 vials of blood reads
 * as 30 successes. That is the whole of "Vial of blood — 1,563 of 0.2 expected", and it dragged a
 * personal score to "luckier than 100% of outcomes". `raidRewards.json` carries no quantity field
 * at all, so unlike npcDrops (whose q/m/n `bundleSize` already divides correctly) there is nothing
 * to divide BY. Listed explicitly rather than guessed: marking an item unscoreable needs only the
 * knowledge that it stacks, while scoring it would need an average nobody here has.
 */
const STACKED_RAID_REWARDS = new Set<number>([
  22446, // Vial of blood — Theatre of Blood pays these in a stack
]);

/** A tier is bulk supply when it is a crowd the collection log almost entirely ignores. */
function supplyTierItems(table: RaidTable, isLogged: (id: number) => boolean): Set<number> {
  const byShare = new Map<number, number[]>();
  for (const item of table.items) {
    byShare.set(item.d, [...(byShare.get(item.d) ?? []), item.i]);
  }
  const supply = new Set<number>();
  for (const ids of byShare.values()) {
    if (ids.length < 5) continue; // a handful sharing a rate is a unique table, not a supply roll
    const logged = ids.filter(isLogged);
    if (logged.length * 2 >= ids.length) continue; // mostly log items — these are the uniques
    for (const id of logged) supply.add(id);
  }
  return supply;
}

export function raidSourcesByItem(overrides?: unknown): Map<number, LuckRateSource[]> {
  const chances = raidUniqueChances(overrides);
  // What the collection log actually lists, which is how a supply tier is told from a unique one.
  const logged = clogItemNames();
  const isLogged = (id: number) => logged.has(id);
  const raw = raidRewards as unknown as Record<string, RaidTable>;
  const tables: Record<string, RaidTable> = { ...raw };
  for (const [key, { base, label }] of Object.entries(SHARES_UNIQUE_TABLE)) {
    if (tables[key] || !raw[base]) continue;
    tables[key] = { ...raw[base], label };
  }
  const out = new Map<number, LuckRateSource[]>();

  for (const [bossKey, table] of Object.entries(tables)) {
    const unique = chances[bossKey];
    if (!Number.isFinite(unique) || unique <= 0) continue;
    const supply = supplyTierItems(table, isLogged);
    for (const item of table.items) {
      if (!Number.isFinite(item.d) || item.d <= 0) continue;
      if (supply.has(item.i) || STACKED_RAID_REWARDS.has(item.i)) continue;
      const list = out.get(item.i) ?? [];
      list.push({
        source: table.label,
        bossKey,
        // Two independent steps: does this raid give me a unique, and is it this one.
        denominator: Math.round(unique * item.d * 100) / 100,
        rolls: 1,
        bundle: 1,
        assumed: true,
      });
      out.set(item.i, list);
    }
  }
  return out;
}
