CREATE TABLE `player_event_facts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`event_id` integer NOT NULL,
	`person_key` text NOT NULL,
	`clan_member_id` integer,
	`user_id` integer,
	`rsn` text NOT NULL,
	`accounts` integer DEFAULT 1 NOT NULL,
	`team_id` integer,
	`points` real DEFAULT 0 NOT NULL,
	`tiles_contributed` integer DEFAULT 0 NOT NULL,
	`tiles_finished` integer DEFAULT 0 NOT NULL,
	`submissions` integer DEFAULT 0 NOT NULL,
	`xp_gained` integer DEFAULT 0 NOT NULL,
	`kc_gained` integer DEFAULT 0 NOT NULL,
	`deaths` integer DEFAULT 0 NOT NULL,
	`loot_gp_gained` integer DEFAULT 0 NOT NULL,
	`pvp_kills` integer DEFAULT 0 NOT NULL,
	`active_days` integer DEFAULT 0 NOT NULL,
	`last_active_day` integer,
	`event_days` integer,
	`subbed_out` integer DEFAULT 0 NOT NULL,
	`team_rank` integer,
	`teams_total` integer,
	`team_points` real,
	`top_team_points` real,
	`detail` text,
	`computed_at` text NOT NULL,
	FOREIGN KEY (`event_id`) REFERENCES `events`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`clan_member_id`) REFERENCES `clan_members`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`team_id`) REFERENCES `teams`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `player_event_facts_event_person_idx` ON `player_event_facts` (`event_id`,`person_key`);--> statement-breakpoint
CREATE INDEX `player_event_facts_person_idx` ON `player_event_facts` (`person_key`);